package com.obsidian.obsidian.cards;

import com.obsidian.obsidian.cards.FsrsService.FsrsState;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;

import static com.obsidian.obsidian.cards.FsrsService.GRADE_EASY;
import static com.obsidian.obsidian.cards.FsrsService.GRADE_GOOD;
import static com.obsidian.obsidian.cards.FsrsService.GRADE_HARD;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.within;

/**
 * Pinned against py-fsrs (FSRS-6, default parameters, desired retention 0.9).
 * Reference values generated by embedder/_fsrs_reference.py — regenerate there
 * if the weights are ever bumped.
 */
class FsrsServiceTest {

    private static final double TOL = 1e-4;

    private FsrsService fsrs;

    @BeforeEach
    void setUp() {
        fsrs = new FsrsService();
        ReflectionTestUtils.setField(fsrs, "desiredRetention", 0.9);
    }

    // ── First review ──────────────────────────────────────────────────────────

    @Test
    void firstReview_hard() {
        FsrsState s = fsrs.initialState(GRADE_HARD);
        assertThat(s.stability()).isCloseTo(1.293100, within(TOL));
        assertThat(s.difficulty()).isCloseTo(5.112171, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(1);
    }

    @Test
    void firstReview_good() {
        FsrsState s = fsrs.initialState(GRADE_GOOD);
        assertThat(s.stability()).isCloseTo(2.306500, within(TOL));
        assertThat(s.difficulty()).isCloseTo(2.118104, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(2);
    }

    @Test
    void firstReview_easy() {
        FsrsState s = fsrs.initialState(GRADE_EASY);
        assertThat(s.stability()).isCloseTo(8.295600, within(TOL));
        assertThat(s.difficulty()).isEqualTo(1.0); // raw D0(Easy) is negative → clamped
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(8);
    }

    // ── Second review (state, grade, elapsed) → py-fsrs reference ─────────────

    @Test
    void goodThenGood_elapsed3() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_GOOD), GRADE_GOOD, 3);
        assertThat(s.stability()).isCloseTo(13.826904, within(TOL));
        assertThat(s.difficulty()).isCloseTo(2.111214, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(14);
    }

    @Test
    void goodThenEasy_elapsed3() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_GOOD), GRADE_EASY, 3);
        assertThat(s.stability()).isCloseTo(23.883064, within(TOL));
        assertThat(s.difficulty()).isEqualTo(1.0);
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(24);
    }

    @Test
    void goodThenHard_elapsed3() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_GOOD), GRADE_HARD, 3);
        assertThat(s.stability()).isCloseTo(9.234871, within(TOL));
        assertThat(s.difficulty()).isCloseTo(4.752858, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(9);
    }

    @Test
    void lateReview_growsStabilityMore() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_GOOD), GRADE_GOOD, 10);
        assertThat(s.stability()).isCloseTo(25.108720, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(25);
    }

    @Test
    void earlyReview_growsStabilityLess() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_GOOD), GRADE_GOOD, 1);
        assertThat(s.stability()).isCloseTo(7.315301, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(7);
    }

    @Test
    void easyThenGood_elapsed15() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_EASY), GRADE_GOOD, 15);
        assertThat(s.stability()).isCloseTo(54.860918, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(55);
    }

    @Test
    void hardThenHard_elapsed2() {
        FsrsState s = fsrs.review(fsrs.initialState(GRADE_HARD), GRADE_HARD, 2);
        assertThat(s.stability()).isCloseTo(4.469455, within(TOL));
        assertThat(s.difficulty()).isCloseTo(6.740460, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(4);
    }

    @Test
    void threeReviewChain() {
        FsrsState s = fsrs.initialState(GRADE_GOOD);
        s = fsrs.review(s, GRADE_GOOD, 3);
        s = fsrs.review(s, GRADE_GOOD, 7);
        assertThat(s.stability()).isCloseTo(39.174976, within(TOL));
        assertThat(s.difficulty()).isCloseTo(2.104331, within(TOL));
        assertThat(fsrs.intervalDays(s.stability())).isEqualTo(39);
    }

    // ── Properties / guards ───────────────────────────────────────────────────

    @Test
    void retrievabilityAtStabilityDaysIs90Percent() {
        assertThat(fsrs.retrievability(10, 10)).isCloseTo(0.9, within(1e-9));
    }

    @Test
    void sameDayReviewDoesNotGrowStability() {
        FsrsState first = fsrs.initialState(GRADE_GOOD);
        FsrsState again = fsrs.review(first, GRADE_GOOD, 0);
        assertThat(again.stability()).isCloseTo(first.stability(), within(TOL));
    }

    @Test
    void againGradeIsRejected_noFireOnFailByDesign() {
        assertThatThrownBy(() -> fsrs.initialState(1))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("no Again");
        assertThatThrownBy(() -> fsrs.review(fsrs.initialState(GRADE_GOOD), 1, 3))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void intervalNeverBelowOneDay() {
        assertThat(fsrs.intervalDays(0.001)).isEqualTo(1);
    }
}
